use std::collections::HashMap;
use std::io::Cursor;
use std::io::Write;
use chrono::Utc;
use serde_json::json;
use zip::write::SimpleFileOptions;
use zip::ZipWriter;
use crate::pipeline::dispatcher::DispatchResult;
use crate::models::MappingResult;

pub struct FritzPackage;

impl FritzPackage {
    pub fn assemble(result: &DispatchResult) -> Result<Vec<u8>, String> {
        let mut buffer = Vec::new();
        let cursor = Cursor::new(&mut buffer);
        let mut zip = ZipWriter::new(cursor);
        let options = SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Deflated);

        // FILE 1: CSRD_Report_Draft.txt
        let csrd_report = generate_csrd_report(result);
        zip.start_file("CSRD_Report_Draft.txt", options)
            .map_err(|e| e.to_string())?;
        zip.write_all(csrd_report.as_bytes()).map_err(|e| e.to_string())?;

        // FILE 2: Audit_Trail_Master.csv
        let audit_trail = generate_audit_trail(result);
        zip.start_file("Audit_Trail_Master.csv", options)
            .map_err(|e| e.to_string())?;
        zip.write_all(audit_trail.as_bytes()).map_err(|e| e.to_string())?;

        // FILE 3: Financial_ESG_Impact.txt
        let financial_impact = generate_financial_impact(result);
        zip.start_file("Financial_ESG_Impact.txt", options)
            .map_err(|e| e.to_string())?;
        zip.write_all(financial_impact.as_bytes()).map_err(|e| e.to_string())?;

        // FILE 4: Gap_Analysis.txt
        let gap_analysis = generate_gap_analysis(result);
        zip.start_file("Gap_Analysis.txt", options)
            .map_err(|e| e.to_string())?;
        zip.write_all(gap_analysis.as_bytes()).map_err(|e| e.to_string())?;

        // FILE 5: 00_ACTION_REQUIRED_Quarantine_Log.csv
        let quarantine_log = generate_quarantine_log(result);
        zip.start_file("00_ACTION_REQUIRED_Quarantine_Log.csv", options)
            .map_err(|e| e.to_string())?;
        zip.write_all(quarantine_log.as_bytes()).map_err(|e| e.to_string())?;

        // MANIFEST: processing_manifest.json
        let manifest = json!({
            "generated_at": Utc::now().to_rfc3339(),
            "targoo_version": "0.1.0",
            "total_rows": result.total_rows,
            "clean_rows": result.clean.len(),
            "best_effort_rows": result.best_effort.len(),
            "quarantined_rows": result.quarantined.len(),
            "total_tco2e": result.total_tco2e,
            "rule_version": "DEFRA_2024",
            "status": "complete"
        });
        zip.start_file("processing_manifest.json", options)
            .map_err(|e| e.to_string())?;
        zip.write_all(manifest.to_string().as_bytes()).map_err(|e| e.to_string())?;

        zip.finish().map_err(|e| e.to_string())?;

        Ok(buffer)
    }
}

fn generate_csrd_report(result: &DispatchResult) -> String {
    let mut report = String::new();
    report.push_str("TARGOO V2 — CSRD REPORT DRAFT\n");
    report.push_str(&format!("Generated: {}\n\n", Utc::now().to_rfc3339()));

    let mut by_target: HashMap<String, f64> = HashMap::new();
    for res in result.clean.iter().chain(result.best_effort.iter()) {
        *by_target.entry(res.esrs_target.clone()).or_insert(0.0) += res.tco2e;
    }

    report.push_str("TOTAL tCO2e BY ESRS TARGET:\n");
    let mut targets: Vec<_> = by_target.keys().collect();
    targets.sort();
    for target in targets {
        report.push_str(&format!("- {}: {:.4} tCO2e\n", target, by_target[target]));
    }

    let total = result.total_rows.max(1);
    report.push_str("\nDATA QUALITY SUMMARY:\n");
    report.push_str(&format!("- Total rows processed: {}\n", result.total_rows));
    report.push_str(&format!("- Clean rows: {} ({:.1}%)\n", result.clean.len(), (result.clean.len() as f64 / total as f64) * 100.0));
    report.push_str(&format!("- Best effort rows: {} ({:.1}%)\n", result.best_effort.len(), (result.best_effort.len() as f64 / total as f64) * 100.0));
    report.push_str(&format!("- Quarantined rows: {} ({:.1}%)\n", result.quarantined.len(), (result.quarantined.len() as f64 / total as f64) * 100.0));
    
    report.push_str("\nFooter: Generated by Targoo V2 ESG Data Refinery\n");
    report
}

fn generate_audit_trail(result: &DispatchResult) -> String {
    let mut wtr = csv::Writer::from_writer(Vec::new());
    let all_results = result.clean.iter()
        .chain(result.best_effort.iter())
        .chain(result.quarantined.iter());

    for res in all_results {
        let _ = wtr.serialize((
            &res.esrs_target,
            &res.raw_header,
            &res.raw_value,
            res.canonical_value,
            &res.canonical_unit,
            res.tco2e,
            res.emission_factor,
            &res.factor_source,
            res.confidence,
            &res.status,
            res.warning.as_deref().unwrap_or(""),
            res.error.as_deref().unwrap_or(""),
        ));
    }
    
    let inner = wtr.into_inner().unwrap_or_default();
    let mut headers = "esrs_target,raw_header,raw_value,canonical_value,canonical_unit,tco2e,emission_factor,factor_source,confidence,status,warning,error\n".to_string();
    headers.push_str(&String::from_utf8_lossy(&inner));
    headers
}

fn generate_financial_impact(result: &DispatchResult) -> String {
    let mut scope1 = 0.0;
    let mut scope2 = 0.0;
    let mut scope3 = 0.0;

    for res in result.clean.iter().chain(result.best_effort.iter()) {
        if res.esrs_target.contains("Scope1") { scope1 += res.tco2e; }
        else if res.esrs_target.contains("Scope2") { scope2 += res.tco2e; }
        else if res.esrs_target.contains("Scope3") { scope3 += res.tco2e; }
    }

    let total = scope1 + scope2 + scope3;
    let mut impact = String::new();
    impact.push_str("FINANCIAL ESG IMPACT SUMMARY\n\n");
    impact.push_str(&format!("Total Scope 1 tCO2e: {:.4}\n", scope1));
    impact.push_str(&format!("Total Scope 2 tCO2e: {:.4}\n", scope2));
    impact.push_str(&format!("Total Scope 3 tCO2e: {:.4}\n", scope3));
    impact.push_str(&format!("Total Emissions: {:.4} tCO2e\n\n", total));
    
    impact.push_str(&format!("Estimated carbon cost at €25/tCO2e:  €{:.2}\n", total * 25.0));
    impact.push_str(&format!("Estimated carbon cost at €65/tCO2e:  €{:.2}\n", total * 65.0));
    impact.push_str(&format!("Estimated carbon cost at €130/tCO2e: €{:.2}\n", total * 130.0));
    
    impact
}

fn generate_gap_analysis(result: &DispatchResult) -> String {
    let required = vec![
        "E1-6_Scope2_Electricity",
        "E1-1_Scope1_NaturalGas",
        "E1-1_Scope1_Diesel",
        "E1-3_Scope3_Road_Freight",
        "E1-2_Scope1_Refrigerants",
    ];

    let present_targets: HashMap<String, bool> = result.clean.iter()
        .chain(result.best_effort.iter())
        .map(|r| (r.esrs_target.clone(), true))
        .collect();

    let mut gap = String::new();
    gap.push_str("CSRD DATA GAP ANALYSIS\n\n");
    
    let mut missing = Vec::new();
    for target in required {
        if !present_targets.contains_key(target) {
            missing.push(target);
            gap.push_str(&format!("MISSING: {} — Data required for CSRD compliance\n", target));
        }
    }

    if missing.is_empty() {
        gap.push_str("All required ESRS targets have data coverage.\n");
    }
    
    gap
}

fn generate_quarantine_log(result: &DispatchResult) -> String {
    if result.quarantined.is_empty() {
        return "esrs_target,raw_header,raw_value,error,confidence,action_required\nNo quarantined items - all data processed successfully\n".to_string();
    }

    let mut wtr = csv::Writer::from_writer(Vec::new());
    for res in &result.quarantined {
        let _ = wtr.serialize((
            &res.esrs_target,
            &res.raw_header,
            &res.raw_value,
            res.error.as_deref().unwrap_or(""),
            res.confidence,
            "Please verify this data point and resubmit",
        ));
    }

    let inner = wtr.into_inner().unwrap_or_default();
    let mut headers = "esrs_target,raw_header,raw_value,error,confidence,action_required\n".to_string();
    headers.push_str(&String::from_utf8_lossy(&inner));
    headers
}
